import { Course, CourseCategory } from '@/services/api';

/**
 * Mock Courses Data - 12 Learning Resources across different categories
 */

export const MOCK_COURSE_CATEGORIES: CourseCategory[] = [
  { id: 1, name: 'Mental Health', description: 'Courses focused on mental wellbeing and stress management' },
  { id: 2, name: 'Career Development', description: 'Professional growth and skill development courses' },
  { id: 3, name: 'Technical Skills', description: 'Technical and domain-specific training' },
  { id: 4, name: 'Leadership', description: 'Leadership and management development' },
  { id: 5, name: 'Communication', description: 'Effective communication and collaboration' },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: 'Managing Stress and Preventing Burnout',
    description: 'Learn practical techniques to manage workplace stress and maintain work-life balance',
    category: MOCK_COURSE_CATEGORIES[0],
    category_names: ['Mental Health'],
    source: 'LinkedIn Learning',
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 2,
    title: 'Building Resilience in the Workplace',
    description: 'Develop mental resilience and coping strategies for challenging situations',
    category: MOCK_COURSE_CATEGORIES[0],
    category_names: ['Mental Health'],
    source: 'Coursera',
    created_at: '2024-01-20T09:00:00Z',
  },
  {
    id: 3,
    title: 'Mindfulness for Professionals',
    description: 'Practice mindfulness techniques to improve focus and reduce anxiety',
    category: MOCK_COURSE_CATEGORIES[0],
    category_names: ['Mental Health'],
    source: 'Udemy',
    created_at: '2024-02-01T09:00:00Z',
  },
  {
    id: 4,
    title: 'Career Planning and Development',
    description: 'Strategic approach to career growth and professional development',
    category: MOCK_COURSE_CATEGORIES[1],
    category_names: ['Career Development'],
    source: 'LinkedIn Learning',
    created_at: '2024-01-10T09:00:00Z',
  },
  {
    id: 5,
    title: 'Negotiation Skills for Career Advancement',
    description: 'Master negotiation techniques for salary, promotions, and opportunities',
    category: MOCK_COURSE_CATEGORIES[1],
    category_names: ['Career Development'],
    source: 'Coursera',
    created_at: '2024-02-05T09:00:00Z',
  },
  {
    id: 6,
    title: 'Personal Branding for Professionals',
    description: 'Build and maintain a strong professional brand',
    category: MOCK_COURSE_CATEGORIES[1],
    category_names: ['Career Development'],
    source: 'Udemy',
    created_at: '2024-02-15T09:00:00Z',
  },
  {
    id: 7,
    title: 'Advanced Python Programming',
    description: 'Deep dive into advanced Python concepts and best practices',
    category: MOCK_COURSE_CATEGORIES[2],
    category_names: ['Technical Skills'],
    source: 'Pluralsight',
    created_at: '2024-01-25T09:00:00Z',
  },
  {
    id: 8,
    title: 'Cloud Architecture Fundamentals',
    description: 'Learn cloud computing principles and architecture patterns',
    category: MOCK_COURSE_CATEGORIES[2],
    category_names: ['Technical Skills'],
    source: 'AWS Training',
    created_at: '2024-02-10T09:00:00Z',
  },
  {
    id: 9,
    title: 'Data Analytics with Power BI',
    description: 'Master data visualization and analytics using Power BI',
    category: MOCK_COURSE_CATEGORIES[2],
    category_names: ['Technical Skills'],
    source: 'Microsoft Learn',
    created_at: '2024-02-20T09:00:00Z',
  },
  {
    id: 10,
    title: 'Leadership Essentials',
    description: 'Core leadership skills for new and aspiring managers',
    category: MOCK_COURSE_CATEGORIES[3],
    category_names: ['Leadership'],
    source: 'LinkedIn Learning',
    created_at: '2024-01-18T09:00:00Z',
  },
  {
    id: 11,
    title: 'Effective Team Communication',
    description: 'Improve team collaboration through better communication',
    category: MOCK_COURSE_CATEGORIES[4],
    category_names: ['Communication'],
    source: 'Coursera',
    created_at: '2024-02-08T09:00:00Z',
  },
  {
    id: 12,
    title: 'Conflict Resolution Strategies',
    description: 'Navigate and resolve workplace conflicts constructively',
    category: MOCK_COURSE_CATEGORIES[4],
    category_names: ['Communication'],
    source: 'Udemy',
    created_at: '2024-02-25T09:00:00Z',
  },
];
