import { Project, ProjectAllocation } from '@/services/api';
import { MOCK_EMPLOYEES } from './team';

/**
 * Mock Projects Data - 20 Projects across 5 Business Units
 */

const businessUnits = ['Supply Chain', 'Merchandising', 'Digital', 'Operations', 'Finance'];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 1,
    title: 'E-Commerce Platform Redesign',
    description: 'Complete overhaul of the customer-facing e-commerce platform with modern UI/UX',
    start_date: '2024-01-15',
    go_live_date: '2024-06-30',
    status: 'Active',
    criticality: 'High',
    source: 'Internal',
    created_at: '2024-01-10T09:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[0].user_info, MOCK_EMPLOYEES[2].user_info, MOCK_EMPLOYEES[5].user_info],
    business_unit: 'Digital',
  },
  {
    id: 2,
    title: 'Supply Chain Optimization',
    description: 'Implement AI-driven supply chain optimization to reduce costs by 15%',
    start_date: '2024-02-01',
    go_live_date: '2024-08-15',
    status: 'Active',
    criticality: 'High',
    source: 'External',
    created_at: '2024-01-25T10:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[1].user_info, MOCK_EMPLOYEES[7].user_info],
    business_unit: 'Supply Chain',
  },
  {
    id: 3,
    title: 'Customer Analytics Dashboard',
    description: 'Build real-time analytics dashboard for customer behavior insights',
    start_date: '2024-01-20',
    go_live_date: '2024-05-30',
    status: 'Active',
    criticality: 'Medium',
    source: 'Internal',
    created_at: '2024-01-15T11:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[3].user_info, MOCK_EMPLOYEES[8].user_info],
    business_unit: 'Digital',
  },
  {
    id: 4,
    title: 'Inventory Management System',
    description: 'Modernize inventory tracking and management across all warehouses',
    start_date: '2024-03-01',
    go_live_date: '2024-09-30',
    status: 'Active',
    criticality: 'High',
    source: 'Internal',
    created_at: '2024-02-20T09:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[4].user_info, MOCK_EMPLOYEES[9].user_info, MOCK_EMPLOYEES[11].user_info],
    business_unit: 'Operations',
  },
  {
    id: 5,
    title: 'Financial Reporting Automation',
    description: 'Automate monthly and quarterly financial reporting processes',
    start_date: '2024-02-15',
    go_live_date: '2024-07-31',
    status: 'Active',
    criticality: 'Medium',
    source: 'Internal',
    created_at: '2024-02-10T10:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[6].user_info, MOCK_EMPLOYEES[10].user_info],
    business_unit: 'Finance',
  },
  {
    id: 6,
    title: 'Product Catalog Expansion',
    description: 'Expand product catalog with 500+ new SKUs and update merchandising strategy',
    start_date: '2024-01-10',
    go_live_date: '2024-06-15',
    status: 'Active',
    criticality: 'Medium',
    source: 'Internal',
    created_at: '2024-01-05T08:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[12].user_info, MOCK_EMPLOYEES[13].user_info],
    business_unit: 'Merchandising',
  },
  {
    id: 7,
    title: 'Mobile App Development',
    description: 'Develop native mobile applications for iOS and Android platforms',
    start_date: '2024-02-20',
    go_live_date: '2024-10-31',
    status: 'Active',
    criticality: 'High',
    source: 'External',
    created_at: '2024-02-15T09:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[0].user_info, MOCK_EMPLOYEES[5].user_info, MOCK_EMPLOYEES[12].user_info],
    business_unit: 'Digital',
  },
  {
    id: 8,
    title: 'Warehouse Automation',
    description: 'Implement robotics and automation in main distribution center',
    start_date: '2024-03-15',
    go_live_date: '2024-11-30',
    status: 'Active',
    criticality: 'High',
    source: 'External',
    created_at: '2024-03-01T10:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[1].user_info, MOCK_EMPLOYEES[7].user_info, MOCK_EMPLOYEES[9].user_info],
    business_unit: 'Operations',
  },
  {
    id: 9,
    title: 'Customer Loyalty Program',
    description: 'Launch new tiered customer loyalty and rewards program',
    start_date: '2024-01-25',
    go_live_date: '2024-05-15',
    status: 'Active',
    criticality: 'Low',
    source: 'Internal',
    created_at: '2024-01-20T11:15:00Z',
    assigned_to: [MOCK_EMPLOYEES[3].user_info, MOCK_EMPLOYEES[6].user_info],
    business_unit: 'Digital',
  },
  {
    id: 10,
    title: 'Vendor Management Portal',
    description: 'Create self-service portal for vendor onboarding and management',
    start_date: '2024-02-10',
    go_live_date: '2024-07-15',
    status: 'Active',
    criticality: 'Medium',
    source: 'Internal',
    created_at: '2024-02-05T09:45:00Z',
    assigned_to: [MOCK_EMPLOYEES[4].user_info, MOCK_EMPLOYEES[11].user_info],
    business_unit: 'Supply Chain',
  },
  {
    id: 11,
    title: 'Budget Planning Tool',
    description: 'Develop collaborative budget planning and forecasting tool',
    start_date: '2024-03-01',
    go_live_date: '2024-08-31',
    status: 'Active',
    criticality: 'Medium',
    source: 'Internal',
    created_at: '2024-02-25T10:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[10].user_info, MOCK_EMPLOYEES[14].user_info],
    business_unit: 'Finance',
  },
  {
    id: 12,
    title: 'Seasonal Campaign Management',
    description: 'Platform for planning and executing seasonal merchandising campaigns',
    start_date: '2024-01-30',
    go_live_date: '2024-06-01',
    status: 'Active',
    criticality: 'Low',
    source: 'Internal',
    created_at: '2024-01-25T08:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[13].user_info],
    business_unit: 'Merchandising',
  },
  {
    id: 13,
    title: 'API Gateway Modernization',
    description: 'Upgrade API gateway infrastructure for better performance and security',
    start_date: '2024-02-25',
    go_live_date: '2024-09-15',
    status: 'Active',
    criticality: 'High',
    source: 'Internal',
    created_at: '2024-02-20T09:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[2].user_info, MOCK_EMPLOYEES[8].user_info],
    business_unit: 'Digital',
  },
  {
    id: 14,
    title: 'Last-Mile Delivery Optimization',
    description: 'Optimize last-mile delivery routes and reduce delivery times',
    start_date: '2024-03-10',
    go_live_date: '2024-10-15',
    status: 'Active',
    criticality: 'Medium',
    source: 'External',
    created_at: '2024-03-05T10:15:00Z',
    assigned_to: [MOCK_EMPLOYEES[1].user_info, MOCK_EMPLOYEES[4].user_info],
    business_unit: 'Supply Chain',
  },
  {
    id: 15,
    title: 'Compliance Reporting System',
    description: 'Automated compliance reporting for regulatory requirements',
    start_date: '2024-02-05',
    go_live_date: '2024-07-20',
    status: 'Active',
    criticality: 'High',
    source: 'Internal',
    created_at: '2024-02-01T09:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[6].user_info, MOCK_EMPLOYEES[10].user_info],
    business_unit: 'Finance',
  },
  {
    id: 16,
    title: 'Price Optimization Engine',
    description: 'AI-powered dynamic pricing engine for competitive advantage',
    start_date: '2024-01-05',
    go_live_date: '2024-05-31',
    status: 'Active',
    criticality: 'Medium',
    source: 'External',
    created_at: '2023-12-28T10:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[12].user_info, MOCK_EMPLOYEES[14].user_info],
    business_unit: 'Merchandising',
  },
  {
    id: 17,
    title: 'Employee Self-Service Portal',
    description: 'Internal portal for HR, payroll, and benefits management',
    start_date: '2024-02-28',
    go_live_date: '2024-08-30',
    status: 'Active',
    criticality: 'Low',
    source: 'Internal',
    created_at: '2024-02-23T09:15:00Z',
    assigned_to: [MOCK_EMPLOYEES[3].user_info, MOCK_EMPLOYEES[8].user_info],
    business_unit: 'Operations',
  },
  {
    id: 18,
    title: 'Demand Forecasting System',
    description: 'Machine learning-based demand forecasting for inventory planning',
    start_date: '2024-03-05',
    go_live_date: '2024-09-30',
    status: 'Active',
    criticality: 'High',
    source: 'External',
    created_at: '2024-03-01T10:00:00Z',
    assigned_to: [MOCK_EMPLOYEES[1].user_info, MOCK_EMPLOYEES[7].user_info, MOCK_EMPLOYEES[9].user_info],
    business_unit: 'Supply Chain',
  },
  {
    id: 19,
    title: 'Data Warehouse Migration',
    description: 'Migrate legacy data warehouse to cloud-based solution',
    start_date: '2024-01-15',
    go_live_date: '2024-06-30',
    status: 'Active',
    criticality: 'Medium',
    source: 'Internal',
    created_at: '2024-01-10T08:45:00Z',
    assigned_to: [MOCK_EMPLOYEES[5].user_info, MOCK_EMPLOYEES[11].user_info],
    business_unit: 'Digital',
  },
  {
    id: 20,
    title: 'Sustainability Reporting Dashboard',
    description: 'Track and report on sustainability metrics and ESG goals',
    start_date: '2024-02-20',
    go_live_date: '2024-07-31',
    status: 'Active',
    criticality: 'Low',
    source: 'Internal',
    created_at: '2024-02-15T09:30:00Z',
    assigned_to: [MOCK_EMPLOYEES[6].user_info, MOCK_EMPLOYEES[14].user_info],
    business_unit: 'Finance',
  },
];

// Project Allocations
export const MOCK_PROJECT_ALLOCATIONS: ProjectAllocation[] = [
  // E-Commerce Platform Redesign allocations
  { id: 1, employee: MOCK_EMPLOYEES[0].user_info, project: MOCK_PROJECTS[0], allocation_percentage: 40, start_date: '2024-01-15', is_active: true, created_at: '2024-01-15T09:00:00Z', updated_at: '2024-01-15T09:00:00Z' },
  { id: 2, employee: MOCK_EMPLOYEES[2].user_info, project: MOCK_PROJECTS[0], allocation_percentage: 50, start_date: '2024-01-15', is_active: true, created_at: '2024-01-15T09:00:00Z', updated_at: '2024-01-15T09:00:00Z' },
  { id: 3, employee: MOCK_EMPLOYEES[5].user_info, project: MOCK_PROJECTS[0], allocation_percentage: 45, start_date: '2024-01-15', is_active: true, created_at: '2024-01-15T09:00:00Z', updated_at: '2024-01-15T09:00:00Z' },
  
  // Supply Chain Optimization allocations
  { id: 4, employee: MOCK_EMPLOYEES[1].user_info, project: MOCK_PROJECTS[1], allocation_percentage: 35, start_date: '2024-02-01', is_active: true, created_at: '2024-02-01T09:00:00Z', updated_at: '2024-02-01T09:00:00Z' },
  { id: 5, employee: MOCK_EMPLOYEES[7].user_info, project: MOCK_PROJECTS[1], allocation_percentage: 40, start_date: '2024-02-01', is_active: true, created_at: '2024-02-01T09:00:00Z', updated_at: '2024-02-01T09:00:00Z' },
  
  // Customer Analytics Dashboard allocations
  { id: 6, employee: MOCK_EMPLOYEES[3].user_info, project: MOCK_PROJECTS[2], allocation_percentage: 30, start_date: '2024-01-20', is_active: true, created_at: '2024-01-20T09:00:00Z', updated_at: '2024-01-20T09:00:00Z' },
  { id: 7, employee: MOCK_EMPLOYEES[8].user_info, project: MOCK_PROJECTS[2], allocation_percentage: 35, start_date: '2024-01-20', is_active: true, created_at: '2024-01-20T09:00:00Z', updated_at: '2024-01-20T09:00:00Z' },
  
  // Additional allocations for other projects
  { id: 8, employee: MOCK_EMPLOYEES[4].user_info, project: MOCK_PROJECTS[3], allocation_percentage: 40, start_date: '2024-03-01', is_active: true, created_at: '2024-03-01T09:00:00Z', updated_at: '2024-03-01T09:00:00Z' },
  { id: 9, employee: MOCK_EMPLOYEES[9].user_info, project: MOCK_PROJECTS[3], allocation_percentage: 35, start_date: '2024-03-01', is_active: true, created_at: '2024-03-01T09:00:00Z', updated_at: '2024-03-01T09:00:00Z' },
  { id: 10, employee: MOCK_EMPLOYEES[11].user_info, project: MOCK_PROJECTS[3], allocation_percentage: 30, start_date: '2024-03-01', is_active: true, created_at: '2024-03-01T09:00:00Z', updated_at: '2024-03-01T09:00:00Z' },
];

// Project Statistics
export const MOCK_PROJECT_STATS = {
  total_projects: 20,
  active_projects: 20,
  high_risk_projects: 8,
  completed_projects: 0,
  completion_rate: 0,
};

// Project Risks Summary
export const MOCK_PROJECT_RISKS = {
  summary: {
    total_projects: 20,
    high_risk_count: 8,
    medium_risk_count: 7,
    low_risk_count: 5,
    risk_percentage: 40,
  },
  projects: MOCK_PROJECTS.filter(p => p.criticality === 'High'),
};

// Business Units
export const MOCK_BUSINESS_UNITS = businessUnits;
