import { EmployeeProfile, User } from '@/services/api';

/**
 * Mock Team Data - 15 Team Members
 * Includes complete employee profiles with mental health, risk scores, and allocations
 */

// Helper to create user info
const createUser = (id: number, firstName: string, lastName: string): User => ({
  id,
  username: `${firstName.toLowerCase()}.${lastName.toLowerCase()}`,
  email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@company.com`,
  first_name: firstName,
  last_name: lastName,
  name: `${firstName} ${lastName}`,
});

export const MOCK_EMPLOYEES: EmployeeProfile[] = [
  {
    id: 1,
    user_info: createUser(1, 'Sarah', 'Johnson'),
    email: 'sarah.johnson@company.com',
    first_name: 'Sarah',
    last_name: 'Johnson',
    name: 'Sarah Johnson',
    age: 32,
    mental_health: 'High',
    motivation_factor: 'Low',
    career_opportunities: 'Medium',
    personal_reason: 'Low',
    manager_assessment_risk: 'High',
    all_triggers: 'MT',
    primary_trigger: 'MT',
    suggested_risk: 'High',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-03-20T14:30:00Z',
    total_allocation: 95,
    project_criticality: 'High',
  },
  {
    id: 2,
    user_info: createUser(2, 'Michael', 'Chen'),
    email: 'michael.chen@company.com',
    first_name: 'Michael',
    last_name: 'Chen',
    name: 'Michael Chen',
    age: 28,
    mental_health: 'Medium',
    motivation_factor: 'High',
    career_opportunities: 'Low',
    personal_reason: 'Medium',
    manager_assessment_risk: 'Medium',
    all_triggers: 'CO,PR',
    primary_trigger: 'CO',
    suggested_risk: 'Medium',
    created_at: '2024-01-10T09:00:00Z',
    updated_at: '2024-03-18T11:20:00Z',
    total_allocation: 80,
    project_criticality: 'Medium',
  },
  {
    id: 3,
    user_info: createUser(3, 'Emily', 'Rodriguez'),
    email: 'emily.rodriguez@company.com',
    first_name: 'Emily',
    last_name: 'Rodriguez',
    name: 'Emily Rodriguez',
    age: 35,
    mental_health: 'Low',
    motivation_factor: 'Medium',
    career_opportunities: 'High',
    personal_reason: 'High',
    manager_assessment_risk: 'High',
    all_triggers: 'MH,PR',
    primary_trigger: 'MH',
    suggested_risk: 'High',
    created_at: '2024-01-05T08:30:00Z',
    updated_at: '2024-03-22T16:45:00Z',
    total_allocation: 110,
    project_criticality: 'High',
  },
  {
    id: 4,
    user_info: createUser(4, 'David', 'Martinez'),
    email: 'david.martinez@company.com',
    first_name: 'David',
    last_name: 'Martinez',
    name: 'David Martinez',
    age: 41,
    mental_health: 'High',
    motivation_factor: 'High',
    career_opportunities: 'High',
    personal_reason: 'Low',
    manager_assessment_risk: 'Low',
    all_triggers: '',
    primary_trigger: undefined,
    suggested_risk: 'Low',
    created_at: '2024-01-20T10:15:00Z',
    updated_at: '2024-03-15T09:30:00Z',
    total_allocation: 75,
    project_criticality: 'Low',
  },
  {
    id: 5,
    user_info: createUser(5, 'Jessica', 'Taylor'),
    email: 'jessica.taylor@company.com',
    first_name: 'Jessica',
    last_name: 'Taylor',
    name: 'Jessica Taylor',
    age: 29,
    mental_health: 'Medium',
    motivation_factor: 'Medium',
    career_opportunities: 'Medium',
    personal_reason: 'Low',
    manager_assessment_risk: 'Low',
    all_triggers: '',
    primary_trigger: undefined,
    suggested_risk: 'Low',
    created_at: '2024-01-12T11:00:00Z',
    updated_at: '2024-03-19T13:15:00Z',
    total_allocation: 85,
    project_criticality: 'Medium',
  },
  {
    id: 6,
    user_info: createUser(6, 'James', 'Anderson'),
    email: 'james.anderson@company.com',
    first_name: 'James',
    last_name: 'Anderson',
    name: 'James Anderson',
    age: 38,
    mental_health: 'Low',
    motivation_factor: 'Low',
    career_opportunities: 'Medium',
    personal_reason: 'High',
    manager_assessment_risk: 'High',
    all_triggers: 'MH,MT,PR',
    primary_trigger: 'MH',
    suggested_risk: 'High',
    created_at: '2024-01-08T09:45:00Z',
    updated_at: '2024-03-21T15:00:00Z',
    total_allocation: 100,
    project_criticality: 'High',
  },
  {
    id: 7,
    user_info: createUser(7, 'Lisa', 'Thompson'),
    email: 'lisa.thompson@company.com',
    first_name: 'Lisa',
    last_name: 'Thompson',
    name: 'Lisa Thompson',
    age: 26,
    mental_health: 'High',
    motivation_factor: 'High',
    career_opportunities: 'Medium',
    personal_reason: 'Low',
    manager_assessment_risk: 'Low',
    all_triggers: '',
    primary_trigger: undefined,
    suggested_risk: 'Low',
    created_at: '2024-01-25T10:30:00Z',
    updated_at: '2024-03-17T12:00:00Z',
    total_allocation: 70,
    project_criticality: 'Low',
  },
  {
    id: 8,
    user_info: createUser(8, 'Robert', 'Wilson'),
    email: 'robert.wilson@company.com',
    first_name: 'Robert',
    last_name: 'Wilson',
    name: 'Robert Wilson',
    age: 44,
    mental_health: 'Medium',
    motivation_factor: 'Low',
    career_opportunities: 'Low',
    personal_reason: 'Medium',
    manager_assessment_risk: 'Medium',
    all_triggers: 'MT,CO',
    primary_trigger: 'MT',
    suggested_risk: 'Medium',
    created_at: '2024-01-18T08:00:00Z',
    updated_at: '2024-03-16T10:45:00Z',
    total_allocation: 90,
    project_criticality: 'Medium',
  },
  {
    id: 9,
    user_info: createUser(9, 'Amanda', 'Garcia'),
    email: 'amanda.garcia@company.com',
    first_name: 'Amanda',
    last_name: 'Garcia',
    name: 'Amanda Garcia',
    age: 31,
    mental_health: 'High',
    motivation_factor: 'Medium',
    career_opportunities: 'High',
    personal_reason: 'Low',
    manager_assessment_risk: 'Low',
    all_triggers: '',
    primary_trigger: undefined,
    suggested_risk: 'Low',
    created_at: '2024-01-22T09:30:00Z',
    updated_at: '2024-03-14T14:20:00Z',
    total_allocation: 80,
    project_criticality: 'Medium',
  },
  {
    id: 10,
    user_info: createUser(10, 'Christopher', 'Lee'),
    email: 'christopher.lee@company.com',
    first_name: 'Christopher',
    last_name: 'Lee',
    name: 'Christopher Lee',
    age: 36,
    mental_health: 'Low',
    motivation_factor: 'Medium',
    career_opportunities: 'Low',
    personal_reason: 'High',
    manager_assessment_risk: 'Medium',
    all_triggers: 'MH,PR',
    primary_trigger: 'MH',
    suggested_risk: 'Medium',
    created_at: '2024-01-14T11:15:00Z',
    updated_at: '2024-03-20T09:00:00Z',
    total_allocation: 95,
    project_criticality: 'High',
  },
  {
    id: 11,
    user_info: createUser(11, 'Jennifer', 'White'),
    email: 'jennifer.white@company.com',
    first_name: 'Jennifer',
    last_name: 'White',
    name: 'Jennifer White',
    age: 27,
    mental_health: 'High',
    motivation_factor: 'High',
    career_opportunities: 'High',
    personal_reason: 'Low',
    manager_assessment_risk: 'Low',
    all_triggers: '',
    primary_trigger: undefined,
    suggested_risk: 'Low',
    created_at: '2024-01-28T10:00:00Z',
    updated_at: '2024-03-13T11:30:00Z',
    total_allocation: 65,
    project_criticality: 'Low',
  },
  {
    id: 12,
    user_info: createUser(12, 'Daniel', 'Brown'),
    email: 'daniel.brown@company.com',
    first_name: 'Daniel',
    last_name: 'Brown',
    name: 'Daniel Brown',
    age: 33,
    mental_health: 'Medium',
    motivation_factor: 'Medium',
    career_opportunities: 'Medium',
    personal_reason: 'Medium',
    manager_assessment_risk: 'Medium',
    all_triggers: 'PR',
    primary_trigger: 'PR',
    suggested_risk: 'Medium',
    created_at: '2024-01-16T09:00:00Z',
    updated_at: '2024-03-19T15:45:00Z',
    total_allocation: 85,
    project_criticality: 'Medium',
  },
  {
    id: 13,
    user_info: createUser(13, 'Michelle', 'Davis'),
    email: 'michelle.davis@company.com',
    first_name: 'Michelle',
    last_name: 'Davis',
    name: 'Michelle Davis',
    age: 39,
    mental_health: 'Low',
    motivation_factor: 'High',
    career_opportunities: 'Medium',
    personal_reason: 'High',
    manager_assessment_risk: 'High',
    all_triggers: 'MH,PR',
    primary_trigger: 'MH',
    suggested_risk: 'High',
    created_at: '2024-01-11T08:30:00Z',
    updated_at: '2024-03-21T10:15:00Z',
    total_allocation: 105,
    project_criticality: 'High',
  },
  {
    id: 14,
    user_info: createUser(14, 'Kevin', 'Miller'),
    email: 'kevin.miller@company.com',
    first_name: 'Kevin',
    last_name: 'Miller',
    name: 'Kevin Miller',
    age: 30,
    mental_health: 'High',
    motivation_factor: 'Medium',
    career_opportunities: 'High',
    personal_reason: 'Low',
    manager_assessment_risk: 'Low',
    all_triggers: '',
    primary_trigger: undefined,
    suggested_risk: 'Low',
    created_at: '2024-01-24T10:45:00Z',
    updated_at: '2024-03-12T13:00:00Z',
    total_allocation: 75,
    project_criticality: 'Low',
  },
  {
    id: 15,
    user_info: createUser(15, 'Rachel', 'Moore'),
    email: 'rachel.moore@company.com',
    first_name: 'Rachel',
    last_name: 'Moore',
    name: 'Rachel Moore',
    age: 34,
    mental_health: 'Medium',
    motivation_factor: 'Low',
    career_opportunities: 'Low',
    personal_reason: 'Medium',
    manager_assessment_risk: 'Medium',
    all_triggers: 'MT,CO',
    primary_trigger: 'MT',
    suggested_risk: 'Medium',
    created_at: '2024-01-19T09:15:00Z',
    updated_at: '2024-03-18T14:30:00Z',
    total_allocation: 90,
    project_criticality: 'Medium',
  },
];

// Team Statistics
export const MOCK_TEAM_STATS = {
  team_members_count: 15,
  average_utilization: 86.3,
  utilization_percentage: '86.3%',
  active_members: 15,
  inactive_members: 0,
};

// Attrition Graph Data (6 months trend)
export const MOCK_ATTRITION_GRAPH_DATA = {
  labels: ['Oct 2023', 'Nov 2023', 'Dec 2023', 'Jan 2024', 'Feb 2024', 'Mar 2024'],
  datasets: [
    {
      label: 'High Risk',
      data: [3, 4, 5, 6, 5, 5],
      backgroundColor: 'rgba(239, 68, 68, 0.8)',
      borderColor: 'rgb(239, 68, 68)',
      borderWidth: 2,
    },
    {
      label: 'Medium Risk',
      data: [4, 5, 4, 5, 6, 5],
      backgroundColor: 'rgba(251, 191, 36, 0.8)',
      borderColor: 'rgb(251, 191, 36)',
      borderWidth: 2,
    },
    {
      label: 'Low Risk',
      data: [8, 6, 6, 4, 4, 5],
      backgroundColor: 'rgba(34, 197, 94, 0.8)',
      borderColor: 'rgb(34, 197, 94)',
      borderWidth: 2,
    },
  ],
};

// Distribution Graph Data
export const MOCK_DISTRIBUTION_GRAPH_DATA = {
  mental_health: {
    labels: ['High', 'Medium', 'Low'],
    data: [7, 4, 4],
    backgroundColor: ['#10B981', '#F59E0B', '#EF4444'],
  },
  motivation: {
    labels: ['High', 'Medium', 'Low'],
    data: [6, 5, 4],
    backgroundColor: ['#10B981', '#F59E0B', '#EF4444'],
  },
  career_opportunities: {
    labels: ['High', 'Medium', 'Low'],
    data: [5, 6, 4],
    backgroundColor: ['#10B981', '#F59E0B', '#EF4444'],
  },
  overall_risk: {
    labels: ['High', 'Medium', 'Low'],
    data: [5, 5, 5],
    backgroundColor: ['#EF4444', '#F59E0B', '#10B981'],
  },
};

// Dashboard Quick Data
export const MOCK_DASHBOARD_QUICK_DATA = {
  team_attrition_risk: 42.5,
  team_mental_health: 68.3,
  avg_utilization: 86.3,
  top_talent: MOCK_EMPLOYEES.filter(e => e.suggested_risk === 'Low').slice(0, 3),
  average_age: 33.5,
};
